import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newGame,act,getCard,comboReady,requiresTarget,previewTarget,type Job} from '../lib/game.ts';
import {jobArchetypes,cardArchetypes,draftContext} from '../lib/archetypes.ts';
function battle(job:Job,hand:string[]){const g=act(newGame(job,false,42),{type:'node',lane:1});g.hand=hand;g.energy=20;g.block=0;g.focus=0;g.draw=Array(10).fill('strike');g.enemies=[{name:'训练目标',hp:200,maxHp:200,block:0,poison:0,weak:0,vuln:0,power:0,offset:0,pattern:[{damage:10,label:'攻击'}]}];return g}
const play=(g:ReturnType<typeof battle>,id:string,target=0)=>act(g,{type:'play',index:g.hand.indexOf(id),target});
test('armor draw requires prior armor, then shield consumes no armor while furnace spends it',()=>{let g=battle('warden',['iron']);g.block=9;g=play(g,'iron');assert.equal(g.hand.length,1);assert.equal(g.block,16);g=battle('warden',['wall','iron','shield','furnace']);g=play(g,'wall');g=play(g,'iron');assert.equal(g.hand.length,4);g=play(g,'shield');assert.equal(g.enemies[0].hp,178);assert.equal(g.block,22);g=play(g,'furnace');assert.equal(g.block,0);assert.equal(g.enemies[0].hp,152)});
test('blood route trades real card life costs for lasting strength and resets each turn',()=>{let g=battle('warden',['blood','rage','laststand']);const hp=g.hp;g=play(g,'blood');assert.equal(g.hp,hp-3);assert.equal(g.bloodPaid,3);g=play(g,'rage');assert.equal(g.strength,3);g=play(g,'laststand');assert.equal(g.enemies[0].hp,183);g=act(g,{type:'end'});assert.equal(g.bloodPaid,0);assert.equal(g.strength,3);g.hand=['rage'];g=play(g,'rage');assert.equal(g.strength,4)});
test('enemy damage, old saves and cost-free upgrades cannot activate blood route; lethal payment stops resolution',()=>{let g=battle('warden',['blood~','rage']);delete g.bloodPaid;g.hp=15;g=play(g,'blood~');g=play(g,'rage');assert.equal(g.strength,1);g=act(g,{type:'end'});assert.equal(g.bloodPaid,0);g=battle('warden',['blood']);g.hp=3;g=play(g,'blood');assert.equal(g.phase,'lost');assert.equal(g.energy,20);assert.equal(g.hp,0)});
test('poison route checks the chosen target before applying its own poison and detonation clears its support',()=>{let g=battle('shade',['venom','whisper','antidote','rupture','antidote']);g=play(g,'venom');g=play(g,'whisper');g=play(g,'antidote');assert.equal(g.block,7);assert.equal(g.enemies[0].poison,8);g=play(g,'rupture');assert.equal(g.enemies[0].poison,0);g=play(g,'antidote');assert.equal(g.block,10);const s=battle('shade',['antidote']);s.enemies[0].poison=4;assert.equal(play(s,'antidote').block,3)});
test('all-target poison and frost bonuses evaluate each enemy independently',()=>{let g=battle('shade',['toxic']);g.enemies.push({...structuredClone(g.enemies[0]),name:'第二目标'});g.enemies[0].poison=5;g=play(g,'toxic');assert.deepEqual(g.enemies.map(e=>e.poison),[13,5]);g=battle('arcanist',['eclipse']);g.enemies.push({...structuredClone(g.enemies[0]),name:'第二目标'});g.enemies[0].weak=2;g=play(g,'eclipse');assert.deepEqual(g.enemies.map(e=>e.hp),[184,192]);assert.deepEqual(g.enemies.map(e=>e.weak),[3,1])});
test('chain route rewards sequencing, and finish has lower standalone damage',()=>{let g=battle('shade',['shiv','cycle','thread','finish']);g=play(g,'shiv');g=play(g,'cycle');const hand=g.hand.length;g=play(g,'thread');assert.equal(g.hand.length,hand+1);assert.equal(g.enemies[0].hp,189);g=play(g,'finish');assert.equal(g.enemies[0].hp,167);assert.equal(play(battle('shade',['finish']),'finish').enemies[0].hp,186)});
test('focus burst and defensive conversion compete for focus, with threshold checked before consumption',()=>{let g=battle('arcanist',['meditate','channel','comet']);g=play(g,'meditate');g=play(g,'channel');const preview=previewTarget(g,g.hand.indexOf('comet'),0)!;assert.equal(preview.damage,39);g=play(g,'comet');assert.equal(g.enemies[0].hp,161);assert.equal(g.focus,0);g=battle('arcanist',['prism','comet']);g.focus=4;g=play(g,'prism');assert.equal(g.block,16);assert.equal(g.focus,0);assert.equal(g.hand.length,2);g=play(g,'comet');assert.equal(g.enemies[0].hp,184)});
test('frost route targets a weakened enemy for defense and the condition decays after enemy action',()=>{let g=battle('arcanist',['frost','barrier','orbit']);assert.equal(requiresTarget(getCard('barrier')),true);g=play(g,'frost');g=play(g,'barrier');assert.equal(g.block,11);g=play(g,'orbit');assert.equal(g.focus,3);g=act(g,{type:'end'});assert.equal(g.enemies[0].weak,1);g.hand=['barrier'];assert.equal(play(g,'barrier').block,7)});
test('targeting a different enemy does not borrow frost bonuses; invalid plays preserve state',()=>{const g=battle('arcanist',['barrier']);g.enemies[0].weak=2;g.enemies.push({...structuredClone(g.enemies[0]),name:'第二目标',weak:0});assert.equal(play(g,'barrier',1).block,7);g.energy=0;assert.equal(play(g,'barrier'),g);assert.equal(act(g,{type:'play',index:0,target:99}),g)});
test('all six routes have obtainable setup and payoff cards, labels and upgrade-compatible rules',()=>{for(const job of ['warden','shade','arcanist'] as Job[]){const routes=jobArchetypes(job);assert.equal(routes.length,2);for(const a of routes){assert.ok(a.setup.some(k=>getCard(k).rarity==='common'));for(const k of [...a.setup,...a.payoff])for(const suffix of ['','+','~']){assert.ok(cardArchetypes(k+suffix).some(r=>r.id===a.id));assert.ok(getCard(k+suffix));}assert.ok(draftContext([],a.payoff[0]).includes('不足'));assert.ok(draftContext([a.setup[0]],a.payoff[0]).includes(getCard(a.setup[0]).name));}}const g=battle('warden',['blood','rage']);const saved=JSON.parse(JSON.stringify(play(g,'blood')));assert.equal(comboReady(saved,getCard('rage')),true)});
