import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newGame,act,getCard,description,CARDS,previewTarget,intent,eventUnavailable,type Game} from '../lib/game.ts';
import {EVENTS} from '../lib/events.ts';
import {choiceConfirmation} from '../lib/choice-confirmation.ts';
function battle(id:string):Game{const s=act(newGame('warden',false,42),{type:'node',lane:1});s.hand=[id];s.energy=10;s.enemies=[{name:'测试',hp:100,maxHp:100,block:0,poison:0,weak:0,vuln:0,power:0,offset:0,pattern:[{damage:10,label:'攻击'}]}];return s}
test('armor combustion spends armor once and preview matches final damage',()=>{const s=battle('furnace');s.block=13;const preview=previewTarget(s,0,0)!;const n=act(s,{type:'play',index:0,target:0});assert.equal(n.block,0);assert.equal(n.enemies[0].hp,83);assert.equal(preview.damage,17);assert.equal(s.block,13);s.hand=['furnace~'];assert.equal(act(s,{type:'play',index:0,target:0}).block,18)});
test('poison detonation consumes poison, bypasses armor and interrupts ritual',()=>{const s=battle('rupture');s.enemies[0].poison=6;s.enemies[0].block=30;s.enemies[0].boss='bishop';s.enemies[0].pattern=[{damage:0,ritual:12,label:'祷告'}];const n=act(s,{type:'play',index:0,target:0});assert.equal(n.enemies[0].block,27);assert.equal(n.enemies[0].hp,88);assert.equal(n.enemies[0].poison,0);assert.equal(intent(n,n.enemies[0]).label,'祷告已打断');assert.deepEqual(n.exhaust,['rupture'])});
test('focus shield trades all focus for armor; tactic saves focus',()=>{const s=battle('prism');s.focus=4;s.block=0;const n=act(s,{type:'play',index:0});assert.equal(n.block,16);assert.equal(n.focus,0);s.hand=['prism~'];const t=act(s,{type:'play',index:0});assert.equal(t.block,7);assert.equal(t.focus,5)});
test('combo scaling caps at three previous cards and bloodied damage uses half health',()=>{const s=battle('thread');s.played=9;assert.equal(act(s,{type:'play',index:0}).enemies[0].hp,87);s.hand=['resolve'];s.hp=s.maxHp/2;assert.equal(act(s,{type:'play',index:0}).enemies[0].hp,85);s.hp++;assert.equal(act(s,{type:'play',index:0}).enemies[0].hp,93)});
test('all new card routes have complete descriptions and resolve without mutating input',()=>{for(const id of Object.keys(CARDS))for(const suffix of ['','+','~']){const key=id+suffix;assert.ok(!description(getCard(key)).includes('undefined'));const s=battle(key),before=structuredClone(s);const n=act(s,{type:'play',index:0,target:0});assert.notEqual(n,s);assert.deepEqual(s,before);assert.ok(n.hp>=0&&n.block>=0&&n.focus>=0);}});
function event(index:number){const s=newGame('shade',false,42);s.phase='event';s.event=index;s.hp=40;s.gold=200;s.deck=['strike','guard','venom+','smoke','thread','rupture','vanish'];return s}
test('all nine events preview without randomness and resolve once',()=>{assert.equal(EVENTS.length,9);for(let i=0;i<EVENTS.length;i++)for(const index of [0,1]){const s=event(i),before=structuredClone(s);assert.ok(choiceConfirmation(s,{type:'event',index})?.detail);assert.deepEqual(s,before);const n=act(s,{type:'event',index});assert.equal(n.phase,'map');assert.equal(act(n,{type:'event',index}),n);assert.ok(n.log[0]);}});
test('event payments reject unavailable trades without spending or consuming RNG',()=>{for(const i of [3,5,6,7,8]){const s=event(i);s.gold=0;assert.ok(eventUnavailable(s));assert.equal(act(s,{type:'event',index:0}),s)}const s=event(6);s.deck=['strike'];assert.equal(act(s,{type:'event',index:0}),s);s.event=3;s.deck=['strike+'];assert.equal(act(s,{type:'event',index:0}),s)});
test('specialist, copy, forgetting and healing trades preserve stated rules',()=>{let s=event(3);const n=act(s,{type:'event',index:0});assert.equal(n.gold,165);assert.equal(n.deck.filter(k=>k.endsWith('~')).length,1);s=event(6);assert.equal(act(s,{type:'event',index:0}).deck.at(-1),'venom+');s=event(7);s.cardsRemoved=2;const forgotten=act(s,{type:'event',index:0});assert.equal(forgotten.deck.length,s.deck.length-1);assert.equal(forgotten.cardsRemoved,2);s=event(4);s.hp=60;const healed=act(s,{type:'event',index:0});assert.equal(healed.maxHp,s.maxHp-5);assert.equal(healed.hp,healed.maxHp);s=event(5);const added=act(s,{type:'event',index:0}).deck.at(-1)!;assert.ok(added.endsWith('~'));assert.equal(getCard(added).job,'shade')});
test('all events can appear through normal seeded nodes and gamble has both outcomes',()=>{const seen=new Set<number>(),outcomes=new Set<string>();for(let seed=1;seed<=100;seed++){let s=newGame('warden',false,seed);s.route[0][1]='event';s=act(s,{type:'node',lane:1});seen.add(s.event);s.event=8;s.gold=25;s.hp=20;const n=act(s,{type:'event',index:0});assert.ok(n.gold===70||n.gold===0);outcomes.add(n.gold===70?'gold':'heal');if(n.gold===0)assert.equal(n.hp,30)}assert.equal(seen.size,EVENTS.length);assert.equal(outcomes.size,2)});
