import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newGame,act,getCard,CARDS,JOBS,RELICS,intent,type Game,type Job} from '../lib/game.ts';
function combat(job:Job='warden'){return act(newGame(job,false,42),{type:'node',lane:1})}
function simple(g:Game){g.enemies=[{name:'测试敌人',hp:100,maxHp:100,block:0,poison:0,weak:0,vuln:0,power:0,pattern:[{damage:10,label:'攻击'}],offset:0}];return g}
test('three different jobs have legal 10-card starter decks and reproducible routes',()=>{for(const job of Object.keys(JOBS) as Job[]){const s=newGame(job,false,42);assert.equal(s.deck.length,10);assert(s.deck.every(k=>CARDS[k]));assert.deepEqual(s.route,newGame(job,false,42).route);assert.equal(s.route.length,15);for(const f of [4,9,14])assert(s.route[f].every(n=>n==='boss'))}assert.notDeepEqual(newGame('warden',false,1).route,newGame('warden',false,2).route)});
test('all 36 cards have valid upgrades',()=>{assert.equal(Object.keys(CARDS).length,36);for(const key of Object.keys(CARDS)){const c=getCard(key),up=getCard(key+'+');assert(up.cost>=0);assert.equal(up.name,c.name+'+');if(c.damage)assert.equal(up.damage,c.damage+3)}});
test('energy blocks unaffordable cards without mutation',()=>{const s=combat();s.hand=['wall'];s.energy=1;const before=structuredClone(s);assert.deepEqual(act(s,{type:'play',index:0}),s);assert.deepEqual(s,before)});
test('shield strike scales with current armor and armor absorbs enemy damage',()=>{const s=simple(combat());s.block=16;s.hand=['shield'];const a=act(s,{type:'play',index:0});assert.equal(a.enemies[0].hp,84);const b=act(a,{type:'end'});assert.equal(b.hp,s.hp);assert.equal(b.block,2)});
test('poison ignores armor, ticks before intent and dead enemies do not attack',()=>{const s=simple(combat('shade'));s.enemies[0].hp=5;s.enemies[0].poison=6;s.enemies[0].block=30;const a=act(s,{type:'end'});assert.equal(a.phase,'reward');assert.equal(a.hp,s.hp);assert.equal(a.enemies[0].hp,0)});
test('vulnerable applies to later damage; weak changes visible and actual enemy intent',()=>{const s=simple(combat());s.hand=['bash','strike'];s.energy=3;let a=act(s,{type:'play',index:0});assert.equal(a.enemies[0].hp,91);a=act(a,{type:'play',index:0});assert.equal(a.enemies[0].hp,82);a.enemies[0].weak=2;assert.equal(intent(a,a.enemies[0]).damage,7);a.block=0;const hp=a.hp;a=act(a,{type:'end'});assert.equal(a.hp,hp-7);assert.equal(a.enemies[0].weak,1)});
test('shade third card draws and combo has its actual payoff',()=>{let s=simple(combat('shade'));s.hand=['shiv','shiv','ambush'];s.draw=['guard'];s.discard=[];s=act(s,{type:'play',index:0});s=act(s,{type:'play',index:0});s=act(s,{type:'play',index:0});assert.equal(s.enemies[0].hp,77);assert.deepEqual(s.hand,['guard'])});
test('arcanist AOE consumes focus once and applies burst to all living enemies',()=>{let s=simple(combat('arcanist'));s.enemies.push(structuredClone(s.enemies[0]));s.focus=4;s.hand=['nova'];s=act(s,{type:'play',index:0});assert.deepEqual(s.enemies.map(e=>e.hp),[76,76]);assert.equal(s.focus,0)});
test('exhausted cards never shuffle into hand; discard reshuffles',()=>{let s=simple(combat());s.hand=['brace'];s.draw=[];s.discard=['guard'];s=act(s,{type:'play',index:0});assert.deepEqual(s.exhaust,['brace']);s=act(s,{type:'end'});assert(!s.hand.includes('brace'));assert(s.hand.includes('guard'))});
test('retain armor survives once, then resets',()=>{let s=simple(combat());s.enemies[0].pattern=[{damage:0,label:'等待'}];s.block=10;s.hand=['hold'];s=act(s,{type:'play',index:0});s=act(s,{type:'end'});assert.equal(s.block,18);s=act(s,{type:'end'});assert.equal(s.block,2)});
test('target selection rejects dead and absent targets; kills auto-select survivor',()=>{let s=simple(combat());s.enemies.push({...structuredClone(s.enemies[0]),hp:1});assert.equal(act(s,{type:'target',index:9}).target,0);s=act(s,{type:'target',index:1});s.hand=['strike'];s=act(s,{type:'play',index:0});assert.equal(s.target,0);assert.equal(s.phase,'battle')});
test('no duplicate victory rewards or postmortem actions',()=>{let s=simple(combat());s.enemies[0].hp=1;s.hand=['strike'];s=act(s,{type:'play',index:0});const gold=s.gold;s=act(s,{type:'end'});assert.equal(s.gold,gold);assert.equal(s.offers.length,3);s=act(s,{type:'reward',index:0});assert.equal(s.deck.length,11);assert.equal(s.phase,'map');const next=act(s,{type:'reward',index:0});assert.deepEqual(next,s)});
test('camp makes exactly one choice and upgrade is permanent',()=>{let s=newGame('warden');s.phase='camp';s.floor=1;s.lane=1;s.route[1][1]='camp';s.hp=20;s=act(s,{type:'upgrade',index:0});assert.equal(s.deck[0],'strike+');assert.equal(s.phase,'map');assert.equal(act(s,{type:'rest'}).hp,20)});
test('merchant payment, stock depletion and minimum deck size are enforced',()=>{let s=newGame('shade');s.phase='shop';s.shop=['venom'];s.gold=100;s=act(s,{type:'buy',index:0});assert.equal(s.gold,55);assert.equal(s.deck.length,11);assert.equal(act(s,{type:'buy',index:0}).gold,55);s=act(s,{type:'remove',index:0});assert.equal(s.gold,0);assert.equal(s.deck.length,10);assert.deepEqual(act(s,{type:'remove',index:0}),s)});
test('route rejects disconnected lanes and jumping floors',()=>{let s=newGame('warden');s.floor=0;s.lane=0;s.phase='map';assert.deepEqual(act(s,{type:'node',lane:2}),s);assert.equal(act(s,{type:'node',lane:1}).floor,1)});
test('lethal enemy attack and lethal event resolve to permanent loss',()=>{let s=simple(combat());s.hp=1;s.block=0;s=act(s,{type:'end'});assert.equal(s.phase,'lost');assert.equal(s.hp,0);assert.deepEqual(act(s,{type:'play',index:0}),s);s=newGame('shade');s.phase='event';s.event=0;s.hp=1;s=act(s,{type:'event',index:0});assert.equal(s.phase,'lost')});
test('boss relics unique; final boss reward completes the run',()=>{let s=simple(combat());s.floor=14;s.lane=1;s.enemies[0].hp=1;s.hand=['strike'];s=act(s,{type:'play',index:0});assert.equal(s.relics.length,1);assert(RELICS.some(r=>r.id===s.relics[0]));assert.equal(s.phase,'reward');s=act(s,{type:'reward',index:-1});assert.equal(s.phase,'won')});
test('relic effects: energy, opening armor, strength, healing, poison and extra draw',()=>{let s=newGame('shade');s.relics=['crown','anchor','stone','ruby','fang','eye'];s=act(s,{type:'node',lane:1});assert.equal(s.energy,4);assert.equal(s.block,10);assert.equal(s.strength,2);assert.equal(s.hand.length,6);s=simple(s);s.hand=['venom'];s=act(s,{type:'play',index:0});assert.equal(s.enemies[0].poison,7);s.enemies[0].hp=1;s.enemies[0].poison=7;const hp=s.hp;s=act(s,{type:'end'});assert.equal(s.hp,Math.min(s.maxHp,hp+4))});
test('hard mode increases enemy health and attack',()=>{const normal=combat();let hard=act(newGame('warden',true,42),{type:'node',lane:1});assert(hard.enemies[0].maxHp>normal.enemies[0].maxHp);const attacks=normal.enemies.flatMap((e,i)=>e.pattern.map((p,j)=>({normal:p.damage,hard:hard.enemies[i].pattern[j].damage})));assert(attacks.every(p=>p.hard>=p.normal));assert(attacks.some(p=>p.hard>p.normal))});
test('serialized mid-battle save resumes deterministically',()=>{const s=combat('arcanist');assert.deepEqual(act(JSON.parse(JSON.stringify(s)),{type:'end'}),act(s,{type:'end'}))});
test('ordinary armor is cleared even when enemies do not attack, without accumulating passive armor',()=>{for(const job of ['warden','shade','arcanist'] as const){let s=simple(combat(job));s.enemies[0].pattern=[{damage:0,label:'等待'}];s.block=40;for(let turn=0;turn<4;turn++){s=act(s,{type:'end'});assert.equal(s.block,job==='warden'?2:0);assert.equal(s.retain,false)}assert(s.log.some(line=>line.includes('清除剩余 40 护甲')))}});
test('retention preserves only leftover armor once and reports the passive separately',()=>{let s=simple(combat());s.block=20;s.retain=true;s=act(s,{type:'end'});assert.equal(s.block,12);assert.equal(s.retain,false);assert(s.log[0].includes('固守保留 10 护甲，铁卫被动 +2'));s.enemies[0].pattern=[{damage:0,label:'等待'}];s=act(s,{type:'end'});assert.equal(s.block,2);assert(s.log[0].includes('清除剩余 12 护甲'))});
test('combat victory does not carry armor or retention into the next encounter',()=>{let s=simple(combat());s.block=40;s.retain=true;s.enemies[0].hp=1;s.hand=['strike'];s=act(s,{type:'play',index:0});s=act(s,{type:'reward',index:-1});s.route[s.floor+1][s.lane]='battle';s=act(s,{type:'node',lane:s.lane});assert.equal(s.block,2);assert.equal(s.retain,false)});
