import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newGame,act,CARDS,getCard,upgradeOptions,isCardKey,isUpgraded,requiresTarget,previewTarget,intent,type Game} from '../lib/game.ts';
import {combatFeedback} from '../lib/combat-feedback.ts';
function boss(floor:number):Game{const g=newGame('warden',false,42);g.floor=floor-1;g.lane=1;return act(g,{type:'node',lane:1})}
test('every card has two different upgrades; preview leaves camp and deck untouched',()=>{for(const key of Object.keys(CARDS)){const g=newGame('warden');g.phase='camp';g.deck=[key];const before=structuredClone(g);const routes=upgradeOptions(key);assert.equal(routes.length,2);assert.notDeepEqual(getCard(routes[0].id),getCard(routes[1].id));assert.deepEqual(g,before);for(const r of routes){assert(isCardKey(r.id));assert(isUpgraded(r.id));assert(getCard(r.id).cost>=0);const next=act(g,{type:'upgrade',index:0,path:r.path});assert.equal(next.deck[0],r.id);assert.equal(next.phase,'map');next.phase='camp';assert.deepEqual(act(next,{type:'upgrade',index:0}),next);assert.deepEqual(upgradeOptions(r.id),[])}}});
test('tactic save keys are valid and malformed keys rejected',()=>{assert(isCardKey('strike~'));assert(isCardKey('strike+'));assert(!isCardKey('strike++'));assert(!isCardKey('strike~+'));const g=boss(4);g.hand=['strike~'];assert.deepEqual(act(JSON.parse(JSON.stringify(g)),{type:'play',index:0,target:0}),act(g,{type:'play',index:0,target:0}))});
test('direct targeting commits atomically and invalid targets spend nothing',()=>{const g=boss(4);g.enemies.push({...structuredClone(g.enemies[0]),boss:undefined,block:0});g.hand=['strike~'];g.energy=0;for(const target of [-1,99,0.5])assert.deepEqual(act(g,{type:'play',index:0,target}),g);const next=act(g,{type:'play',index:0,target:1});assert.equal(next.enemies[0].hp,g.enemies[0].hp);assert.equal(next.enemies[1].hp,g.enemies[1].hp-4);assert.equal(next.energy,0)});
test('preview is pure and agrees with committed target damage',()=>{const g=boss(4);g.hand=['bash'];const original=structuredClone(g);const p=previewTarget(g,0,0)!;const next=act(g,{type:'play',index:0,target:0});assert.deepEqual(g,original);assert.equal(p.damage,g.enemies[0].hp-next.enemies[0].hp);assert.equal(p.blocked,g.enemies[0].block-next.enemies[0].block)});
test('piercing bypasses armor without breaking ironjaw guard; focus preservation rounds down',()=>{const g=boss(4);g.hand=['shiv~'];let next=act(g,{type:'play',index:0,target:0});assert.equal(next.enemies[0].block,12);assert.equal(next.enemies[0].hp,g.enemies[0].hp-4);assert(!next.enemies[0].staggered);g.hand=['bolt~'];g.focus=5;next=act(g,{type:'play',index:0,target:0});assert.equal(next.focus,2);assert.equal(next.enemies[0].hp,g.enemies[0].hp-8)});
test('single-target status cards require a target but upgraded AOE does not',()=>{assert(requiresTarget(getCard('smoke')));assert(!requiresTarget(getCard('smoke~')));assert(!requiresTarget(getCard('guard')));assert(requiresTarget(getCard('venom~')))});
test('breaking ironjaw armor cancels one action, then its armor stance returns',()=>{let g=boss(4);g.hand=['slam'];g=act(g,{type:'play',index:0,target:0});assert(g.enemies[0].staggered);assert.equal(intent(g,g.enemies[0]).damage,0);const hp=g.hp;g=act(g,{type:'end'});assert.equal(g.hp,hp);assert.equal(g.enemies[0].staggered,false);g=act(g,{type:'end'});assert.equal(g.enemies[0].block,16)});
test('bishop summon has no immediate attack and is limited to one living minion',()=>{let g=boss(9);g.turn=2;const hp=g.hp;g=act(g,{type:'end'});assert.equal(g.hp,hp);assert.equal(g.enemies.length,2);assert(g.enemies[1].minion);g.turn=5;g.block=0;g=act(g,{type:'end'});assert.equal(g.enemies.length,2);assert.equal(g.hp,hp-7)});
test('bishop ritual can be interrupted by attacks or poison, progress resets next turn',()=>{for(const poison of [false,true]){let g=boss(9);g.turn=2;if(poison)g.enemies[0].poison=12;else{g.hand=['slam'];g=act(g,{type:'play',index:0,target:0});assert.equal(intent(g,g.enemies[0]).label,'祷告已打断')}g=act(g,{type:'end'});assert.equal(g.enemies.length,1);assert.equal(g.enemies[0].pressure,0)}});
test('poison killing bishop immediately banishes its minion with no phantom attack',()=>{let g=boss(9);g.turn=2;g=act(g,{type:'end'});g.enemies[0].hp=2;g.enemies[0].poison=2;const hp=g.hp;const next=act(g,{type:'end'});assert.equal(next.phase,'reward');assert.equal(next.hp,hp);assert.equal(next.enemies[1].hp,0);assert.equal(combatFeedback(g,next,{type:'end'}).attackers.length,0)});
test('ash king enters phase two and punishes only the fourth card, once per turn',()=>{let g=boss(14);g.enemies[0].hp=Math.ceil(g.enemies[0].maxHp/2)+1;g.hand=['strike','guard','guard','guard','guard'];g.energy=10;g=act(g,{type:'play',index:0,target:0});assert(g.enemies[0].enraged);const hp=g.hp;g=act(g,{type:'play',index:0});g=act(g,{type:'play',index:0});assert.equal(g.hp,hp);g=act(g,{type:'play',index:0});assert.equal(g.hp,hp-4);g=act(g,{type:'play',index:0});assert.equal(g.hp,hp-4)});
test('killing ash king with the fourth card prevents retaliation',()=>{const g=boss(14);g.enemies[0].enraged=true;g.enemies[0].hp=1;g.played=3;g.hand=['strike'];g.hp=3;const next=act(g,{type:'play',index:0,target:0});assert.equal(next.phase,'reward');assert.equal(next.hp,g.hp)});
