import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newTutorial,tutorialAllows} from '../lib/tutorial.ts';
import {act,newGame,type Action} from '../lib/game.ts';
import {soundCues,BattleAudio} from '../lib/battle-audio.ts';

test('tutorial completes a real block, attack, enemy turn, kill and reward with no health loss',()=>{const adventure=newGame('shade',true,99),saved=JSON.stringify(adventure);let g=newTutorial(),step=0;const initialHp=g.hp;const actions:Action[]=[{type:'target',index:0},{type:'play',index:0},{type:'play',index:0},{type:'end'}];for(const a of actions){assert(tutorialAllows(step,g,a));g=act(g,a);step++}assert.equal(g.hp,initialHp);assert.equal(g.energy,3);assert.equal(g.turn,2);assert.equal(g.hand.length,5);const kill={type:'play',index:g.hand.indexOf('strike')} as const;assert(tutorialAllows(step,g,kill));g=act(g,kill);assert.equal(g.phase,'reward');assert.equal(g.enemies[0].hp,0);assert(tutorialAllows(5,g,{type:'reward',index:0}));g=act(g,{type:'reward',index:0});assert.equal(g.phase,'map');assert.equal(JSON.stringify(adventure),saved)});
test('tutorial blocks premature endings and wrong cards, supports skipping rewards',()=>{const g=newTutorial();assert(!tutorialAllows(0,g,{type:'end'}));assert(!tutorialAllows(1,g,{type:'play',index:1}));assert(!tutorialAllows(2,g,{type:'play',index:99}));assert(tutorialAllows(5,g,{type:'reward',index:-1}));assert(!tutorialAllows(6,g,{type:'target',index:0}))});
test('sound timeline distinguishes player damage, monster damage, block and spell',()=>{const cues=soundCues({duration:1000,attackers:[{target:-1,delay:0},{target:0,delay:400}],impacts:[{target:0,kind:'magic',amount:5,delay:80},{target:1,kind:'magic',amount:5,delay:80},{target:-1,kind:'guard',amount:2,delay:480},{target:-1,kind:'slash',amount:8,delay:480}]});assert.deepEqual(cues,[{kind:'cast',delay:0},{kind:'swing',delay:400},{kind:'hit',delay:80},{kind:'block',delay:480},{kind:'hurt',delay:480}])});
test('audio stays inert while muted and gracefully handles unsupported browsers',()=>{const audio=new BattleAudio();audio.setEnabled(false);audio.play({duration:650,attackers:[{target:-1,delay:0}],impacts:[]});audio.setEnabled(true);assert.doesNotThrow(()=>audio.unlock());assert.doesNotThrow(()=>audio.dispose())});
test('hard mode uses multiplicative health and damage scaling in every act',()=>{for(const floor of [4,9,14]){let normal=newGame('warden',false,9);normal.floor=floor-1;normal.lane=1;let hard={...structuredClone(normal),hard:true};normal=act(normal,{type:'node',lane:1});hard=act(hard,{type:'node',lane:1});const scale=1+Math.floor(floor/5)*.4;assert.equal(hard.enemies[0].maxHp,Math.round(95*1.27*scale*1.10));assert.equal(hard.enemies[0].pattern[0].damage,Math.round(9*1.20*(1+Math.floor(floor/5)*.22)*1.08))}});
test('relic pool never awards an unusable poison relic to warden or arcanist',()=>{for(const job of ['warden','arcanist','shade'] as const){let g=newGame(job,false,33);for(let i=0;i<9;i++){g.phase='event';g.event=0;g.hp=100;g.maxHp=100;g=act(g,{type:'event',index:0})}assert.equal(g.relics.includes('fang'),job==='shade')}});
test('sound sources use effect delays and muting cancels scheduled hits',()=>{const previous=globalThis.AudioContext;const starts:number[]=[],stops:number[]=[];const param=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}});const node=()=>({connect(){},disconnect(){}});const voice=()=>({...node(),onended:null,start(t:number){starts.push(t)},stop(t?:number){if(t===undefined)stops.push(1)}});class MockContext{currentTime=10;sampleRate=8000;destination={};resume(){return Promise.resolve()}close(){return Promise.resolve()}createGain(){return {...node(),gain:param()}}createOscillator(){return {...voice(),type:'sine',frequency:param()}}createBuffer(){return {getChannelData:()=>new Float32Array(720)}}createBufferSource(){return {...voice(),buffer:null}}createBiquadFilter(){return {...node(),type:'lowpass',frequency:param()}}}try{globalThis.AudioContext=MockContext as unknown as typeof AudioContext;const audio=new BattleAudio();audio.play({duration:1000,attackers:[],impacts:[{target:-1,kind:'slash',amount:3,delay:480}]});assert(starts.length>=1);assert(starts.every(t=>t===10.48));audio.setEnabled(false);assert.equal(stops.length,starts.length);const count=starts.length;audio.play({duration:600,attackers:[{target:-1,delay:0}],impacts:[]});assert.equal(starts.length,count);audio.dispose()}finally{globalThis.AudioContext=previous}});
test('lethal sacrifice is resolved before a healing relic can rescue the player',()=>{const g=newGame('warden',false,100);g.phase='event';g.event=0;g.hp=9;g.relics=['ruby','anchor','eye','coin','crown','stone'];const next=act(g,{type:'event',index:0});assert.equal(next.phase,'lost');assert.equal(next.hp,0);assert(!next.relics.includes('heart'));assert.equal(next.maxHp,g.maxHp)});
