'use client';
import {useEffect,useRef,useState} from 'react';
import {Shield,Swords,Heart,Zap,ArrowRight} from 'lucide-react';
import {act,getCard,description,requiresTarget,type Action} from '../lib/game';
import {newTutorial,tutorialAllows,TUTORIAL_STEPS} from '../lib/tutorial';
import {combatFeedback,type CombatFeedback} from '../lib/combat-feedback';
import {PixelFighter,BattleImpacts} from './pixel-fighter';

export function Tutorial({onDone,onSound}:{onDone:()=>void;onSound:(fx:CombatFeedback)=>void}){
  const[reward,setReward]=useState<number|null>(null);const[selected,setSelected]=useState<number|null>(null);const[g,setG]=useState(newTutorial);const[step,setStep]=useState(0);const[fx,setFx]=useState<CombatFeedback|null>(null);const[serial,setSerial]=useState(0);
  const timer=useRef<ReturnType<typeof setTimeout>|null>(null),busy=useRef(false);
  useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
  function send(a:Action){if(busy.current||!tutorialAllows(step,g,a))return;setSelected(null);const next=act(g,a);if(a.type==='play'||a.type==='end'){const f=combatFeedback(g,next,a);setFx(f);setSerial(n=>n+1);onSound(f);busy.current=true;timer.current=setTimeout(()=>{busy.current=false;setFx(null)},f.duration)}setG(next);setStep(s=>s+1)}
  const instruction=TUTORIAL_STEPS[step];
  return <section className="tutorial"><div className="tutorial-progress" aria-label={`教程第 ${step+1} 步，共 7 步`}>{TUTORIAL_STEPS.map((_,i)=><span key={i} className={i<=step?'complete':''}/>)}</div><div className="tutorial-instruction" aria-live="polite"><span>练习 {step+1} / 7 · 不影响冒险存档</span><h2>{instruction.title}</h2><p>{instruction.text}</p></div>{step<6?<><div className="training-stage"><div className="training-player"><b>铁卫</b><div className="sprite-emblem" key={serial}><PixelFighter name="warden" feedback={fx??undefined}/><BattleImpacts feedback={fx??undefined} target={-1}/></div><span><Heart size={15}/>{g.hp}/{g.maxHp} <Shield size={15}/>{g.block}</span></div><button className={'training-enemy'+(step===0?' prompted':'')} onClick={()=>selected!==null?send({type:'play',index:selected,target:0}):send({type:'target',index:0})} disabled={!!fx||(step!==0&&selected===null)}><span><Swords size={16}/> 6 点攻击</span><div className="sprite-emblem" key={serial}><PixelFighter name="失魂士兵" feedback={fx??undefined} target={0}/><BattleImpacts feedback={fx??undefined} target={0}/></div><b>{g.enemies[0].hp>0?'训练骷髅':'已击败'} · {g.enemies[0].hp}/12</b></button></div><div className="training-energy"><Zap size={18}/> 能量 {g.energy} / 3 <span>{fx?'观察战斗结算…':g.log[0]}</span></div>{step<5?<div className="training-hand">{g.hand.map((id,i)=>{const c=getCard(id);return <button className={'playingcard '+c.kind+(selected===i?' aiming-card':'')} key={i} disabled={!!fx||!tutorialAllows(step,g,{type:'play',index:i})} onClick={()=>requiresTarget(c)?setSelected(i):send({type:'play',index:i})}><div className="cardhead"><span className="cost">{c.cost}</span>{selected===i?'点击骷髅施放':c.kind}</div><h3>{c.name}</h3><p>{description(c)}</p></button>})}</div>:<div className="training-hand">{g.offers.map((id,i)=><button key={id} className="option" disabled={!!fx} aria-pressed={reward===i} onClick={()=>setReward(i)}><h3>{getCard(id).name}</h3><p>{description(getCard(id))}</p><small>加入牌组</small></button>)}</div>}<div className="actions center">{step<5?<button className="primary" disabled={step!==3||!!fx} onClick={()=>send({type:'end'})}>结束回合 <ArrowRight size={17}/></button>:<button className="secondary" disabled={!!fx} aria-pressed={reward===-1} onClick={()=>setReward(-1)}>选择跳过奖励</button>}</div>{step===5&&reward!==null&&<div className="tutorial-reward-confirm"><p>{reward===-1?'不添加卡牌，完成练习。':`加入 ${getCard(g.offers[reward]).name}，放弃其余奖励。`}</p><button className="primary" disabled={!!fx} onClick={()=>send({type:'reward',index:reward})}>确定</button></div>}</>:<div className="tutorial-complete"><Shield size={45}/><p>你已经完成一次防御、攻击、回合结算、击杀与选牌。</p><button className="primary" onClick={onDone}>完成教程，选择职业 <ArrowRight size={18}/></button></div>}</section>;
}
