import {EVENTS} from './events.ts';
export type Job='warden'|'shade'|'arcanist';
export type Card={id:string;name:string;job:Job|'any';cost:number;kind:'攻击'|'技能'|'能力';icon:string;damage?:number;block?:number;poison?:number;weak?:number;vuln?:number;draw?:number;energy?:number;strength?:number;focus?:number;burst?:boolean;shieldStrike?:boolean;combo?:boolean;all?:boolean;exhaust?:boolean;heal?:number;hpCost?:number;retain?:boolean;piercing?:boolean;conserveFocus?:boolean;burnArmor?:boolean;detonate?:number;focusShield?:number;perPlayed?:number;bloodied?:number};
export const CARDS:Record<string,Card>={};
function card(id:string,name:string,job:Card['job'],cost:number,kind:Card['kind'],icon:string,e:Partial<Card>){CARDS[id]={id,name,job,cost,kind,icon,...e}}
card('strike','斩击','any',1,'攻击','sword',{damage:6});card('guard','格挡','any',1,'技能','shield',{block:5});
card('bash','破甲重击','warden',2,'攻击','sword',{damage:9,vuln:2});card('shield','盾击','warden',1,'攻击','shield',{shieldStrike:true});card('wall','壁垒','warden',2,'技能','shield',{block:15});card('rage','战意','warden',1,'能力','flame',{strength:2,exhaust:true});card('iron','钢铁意志','warden',1,'技能','shield',{block:7,draw:1});card('cleave','横扫','warden',1,'攻击','sword',{damage:7,all:true});card('hold','固守','warden',1,'技能','shield',{block:6,retain:true});card('blood','血铸','warden',0,'技能','flame',{hpCost:3,energy:2,exhaust:true});card('slam','震地','warden',2,'攻击','sword',{damage:16,weak:2});card('rally','重整旗鼓','warden',1,'技能','flame',{heal:6,exhaust:true});
card('venom','淬毒','shade',1,'技能','poison',{poison:5});card('shiv','快刃','shade',0,'攻击','sword',{damage:4});card('ambush','伏击','shade',1,'攻击','sword',{damage:7,combo:true});card('smoke','烟幕','shade',1,'技能','moon',{block:8,weak:1});card('toxic','毒雾','shade',2,'技能','poison',{poison:6,all:true});card('cycle','潜行','shade',0,'技能','moon',{draw:2,exhaust:true});card('dance','刃舞','shade',1,'攻击','sword',{damage:5,draw:1});card('mark','猎杀印记','shade',0,'技能','moon',{vuln:2,exhaust:true});card('escape','脱身','shade',1,'技能','moon',{block:6,draw:1});card('finish','终结','shade',2,'攻击','sword',{damage:18,combo:true});
card('bolt','灵火','arcanist',1,'攻击','spark',{damage:7,burst:true});card('meditate','冥想','arcanist',1,'技能','spark',{focus:3,block:4});card('nova','星陨','arcanist',2,'攻击','spark',{damage:12,burst:true,all:true});card('barrier','符文屏障','arcanist',1,'技能','shield',{block:9});card('insight','洞见','arcanist',0,'技能','spark',{draw:2,exhaust:true});card('channel','引流','arcanist',0,'技能','spark',{focus:2,hpCost:2});card('frost','寒霜','arcanist',1,'攻击','moon',{damage:5,weak:2});card('surge','法力潮汐','arcanist',0,'技能','spark',{energy:2,exhaust:true});card('comet','彗星','arcanist',2,'攻击','spark',{damage:20,burst:true});card('aegis','星幕','arcanist',2,'技能','shield',{block:16,focus:2});
card('prepare','整备','any',1,'技能','book',{draw:3});card('pierce','精准刺击','any',1,'攻击','sword',{damage:8,vuln:1});card('brace','坚韧','any',0,'技能','shield',{block:4,exhaust:true});card('renew','回春','any',1,'技能','flame',{heal:7,exhaust:true});

card('furnace','熔炉重拳','warden',1,'攻击','flame',{damage:4,burnArmor:true});
card('laststand','背水列阵','warden',1,'攻击','shield',{damage:7,block:5,bloodied:7});
card('bulwark','移动要塞','warden',3,'技能','shield',{block:24,retain:true,exhaust:true});
card('warcry','战吼回响','warden',1,'技能','flame',{weak:2,all:true,draw:1,exhaust:true});
card('oath','血誓铸甲','warden',0,'技能','shield',{hpCost:4,block:11,exhaust:true});
card('march','钢铁行军','warden',1,'攻击','sword',{damage:5,block:4,perPlayed:2});
card('rupture','毒囊破裂','shade',1,'攻击','poison',{damage:3,detonate:2,exhaust:true});
card('thread','牵丝刃','shade',1,'攻击','moon',{damage:4,perPlayed:3});
card('antidote','以毒为幕','shade',1,'技能','poison',{block:6,poison:3});
card('whisper','无声蔓延','shade',1,'技能','poison',{poison:3,all:true,exhaust:true});
card('desperate','绝境闪击','shade',0,'攻击','sword',{damage:3,bloodied:6,exhaust:true});
card('vanish','烟中换位','shade',1,'技能','moon',{block:4,draw:2,exhaust:true});
card('prism','折光结界','arcanist',1,'技能','shield',{block:4,focusShield:3});
card('orbit','环星术','arcanist',1,'攻击','spark',{damage:6,focus:2});
card('eclipse','蚀日咒','arcanist',2,'攻击','moon',{damage:10,weak:2,all:true,exhaust:true});
card('embers','余烬编织','arcanist',0,'技能','flame',{hpCost:3,focus:3,exhaust:true});
card('starlance','星轨长枪','arcanist',2,'攻击','spark',{damage:8,burst:true,piercing:true,exhaust:true});
card('sundial','日晷回拨','arcanist',1,'技能','book',{focus:2,draw:2,exhaust:true});
card('gamble','孤注一掷','any',0,'技能','coin',{hpCost:4,draw:2,exhaust:true});
card('provision','战地口粮','any',1,'技能','heart',{heal:4,block:4,exhaust:true});
card('feint','佯攻','any',0,'攻击','sword',{damage:2,weak:1,exhaust:true});
card('momentum','乘胜追击','any',1,'攻击','sword',{damage:5,perPlayed:2});
card('resolve','残火意志','any',1,'攻击','flame',{damage:7,bloodied:8});
card('shelter','临时掩体','any',2,'技能','shield',{block:14,draw:1,exhaust:true});
export type UpgradePath='power'|'tactic';
export function isUpgraded(key:string){return /[+~]$/.test(key)}
export function baseCardId(key:string){return key.replace(/[+~]$/,'')}
export function isCardKey(key:string){return typeof key==='string'&&Object.hasOwn(CARDS,baseCardId(key))}
const TACTICS:Record<string,Partial<Card>>={

  furnace:{name:'冷铸重拳',burnArmor:false,damage:7,block:5},laststand:{name:'背水突围',block:0,cost:0,exhaust:true},bulwark:{name:'要塞展开',cost:2,block:16},warcry:{name:'恐惧回响',draw:0,vuln:2},oath:{name:'不屈血誓',hpCost:2,block:8},march:{name:'急行军',perPlayed:1,draw:1},
  rupture:{name:'毒刃穿心',detonate:0,damage:6,poison:4,piercing:true},thread:{name:'缠绕丝刃',perPlayed:2,weak:1},antidote:{name:'毒幕驻留',block:4,retain:true},whisper:{name:'蔓延恐惧',poison:2,weak:1},desperate:{name:'绝境脱身',bloodied:0,block:5},vanish:{name:'隐遁',draw:1,retain:true},
  prism:{name:'棱镜蓄能',focusShield:0,block:7,focus:1},orbit:{name:'引力环',damage:4,focus:1,all:true},eclipse:{name:'长夜降临',damage:7,weak:3},embers:{name:'冷焰编织',hpCost:0,focus:2},starlance:{name:'折返星枪',damage:5,conserveFocus:true},sundial:{name:'逆转时针',focus:0,cost:0},
  gamble:{name:'谨慎下注',hpCost:0,draw:1},provision:{name:'应急口粮',cost:0,heal:3,block:0},feint:{name:'虚实交错',weak:0,vuln:1,draw:1},momentum:{name:'追击步法',perPlayed:1,block:5},resolve:{name:'残火续燃',bloodied:0,heal:3,exhaust:true},shelter:{name:'隐蔽工事',block:10,retain:true,draw:0},
  strike:{name:'轻击',cost:0,damage:4},guard:{name:'驻守',retain:true},
  bash:{name:'破甲突刺',cost:1,damage:6,vuln:1},shield:{name:'攻防一体',block:3},wall:{name:'不动壁垒',block:12,retain:true},rage:{name:'战术号令',draw:2},iron:{name:'钢铁蓄势',energy:1},cleave:{name:'破阵横扫',piercing:true},hold:{name:'固守待援',draw:1},blood:{name:'无痛血铸',hpCost:0,draw:1},slam:{name:'震慑全场',damage:10,all:true},rally:{name:'重整阵线',block:8},
  venom:{name:'速效淬毒',cost:0,poison:3},shiv:{name:'穿甲快刃',piercing:true},ambush:{name:'伏击破绽',vuln:2},smoke:{name:'迷踪烟幕',all:true},toxic:{name:'腐蚀毒雾',weak:1},cycle:{name:'潜行架势',block:5},dance:{name:'连环刃舞',cost:0,damage:3,exhaust:true},mark:{name:'猎杀毒印',poison:3},escape:{name:'蓄势脱身',retain:true},finish:{name:'致命终结',piercing:true},
  bolt:{name:'余韵灵火',damage:5,conserveFocus:true},meditate:{name:'快速冥想',cost:0,focus:2,block:2},nova:{name:'寒星坠落',damage:10,weak:1},barrier:{name:'持续屏障',block:7,retain:true},insight:{name:'聚灵洞见',focus:2},channel:{name:'无损引流',hpCost:0},frost:{name:'冰封领域',damage:3,all:true},surge:{name:'灵能潮汐',focus:3},comet:{name:'穿云彗星',damage:17,piercing:true},aegis:{name:'星幕回响',block:13,draw:2},
  prepare:{name:'轻装整备',cost:0,draw:2,exhaust:true},pierce:{name:'贯穿刺击',piercing:true},brace:{name:'随行坚韧',draw:1},renew:{name:'回春护佑',block:6},
};
export function getCard(key:string):Card{
  const c=CARDS[baseCardId(key)];if(!c)throw Error('未知卡牌');
  if(key.endsWith('~'))return {...c,...TACTICS[c.id],id:key,name:TACTICS[c.id].name+'·改'};
  if(!key.endsWith('+'))return c;
  const u={...c,id:key,name:c.name+'+'};
  for(const field of ['damage','block','heal'] as const)if(u[field])u[field]!+=3;
  for(const field of ['poison','weak','vuln','draw','strength','focus'] as const)if(u[field])u[field]!+=1;
  if(c.shieldStrike||c.retain||c.energy)u.cost=Math.max(0,c.cost-1);return u;
}
export function upgradeOptions(key:string){return isUpgraded(key)?[]:[{path:'power' as const,id:key+'+',label:'强化 · 数值提升'},{path:'tactic' as const,id:key+'~',label:'专精 · 改变打法'}]}
export function requiresTarget(c:Card){return !c.all&&!!(c.damage||c.shieldStrike||c.detonate||c.poison||c.weak||c.vuln)}
export function description(c:Card){return [c.burnArmor&&'消耗全部自身护甲，等量增加本次攻击伤害',c.detonate&&`攻击后引爆目标全部中毒，每层造成 ${c.detonate} 点无视护甲的生命伤害`,c.focusShield&&`消耗全部灵力，每层获得 ${c.focusShield} 点护甲`,c.perPlayed&&`本回合每已出一张牌，额外造成 ${c.perPlayed} 点伤害（最多计算 3 张）`,c.bloodied&&`生命不高于一半时，额外造成 ${c.bloodied} 点伤害`,c.damage&&`造成 ${c.damage} 点伤害`,c.shieldStrike&&'造成等同当前护甲的伤害',c.combo&&'若本回合已出 2 张牌，额外造成 8 点伤害',c.burst&&(c.conserveFocus?'按全部灵力加伤，每层 +3；仅消耗一半灵力（向上取整）':'消耗全部灵力，每层额外造成 3 点伤害'),c.piercing&&'穿甲：攻击无视敌人护甲',c.block&&`获得 ${c.block} 点护甲`,c.poison&&`施加 ${c.poison} 层中毒`,c.weak&&`施加 ${c.weak} 回合虚弱`,c.vuln&&`施加 ${c.vuln} 回合易伤`,c.draw&&`抽 ${c.draw} 张牌`,c.energy&&`获得 ${c.energy} 点能量`,c.strength&&`本场获得 ${c.strength} 点力量`,c.focus&&`获得 ${c.focus} 层灵力`,c.heal&&`恢复 ${c.heal} 点生命`,c.hpCost&&`失去 ${c.hpCost} 点生命`,c.retain&&'护甲保留至下一回合',c.all&&'作用于所有敌人',c.exhaust&&'消耗：本场战斗不再出现'].filter(Boolean).join('。')+'。'}
export const JOBS={warden:{name:'铁卫',en:'THE WARDEN',hp:78,color:'#e5a658',tag:'护甲 · 反击',text:'让每一道伤痕，成为下一击的力量。',passive:'坚守：每回合开始获得 2 点护甲。',deck:['strike','strike','strike','guard','guard','guard','bash','shield','iron','wall']},shade:{name:'影刃',en:'THE SHADE',hp:64,color:'#87c7a0',tag:'连击 · 毒素',text:'刀锋未至，毒已入骨。',passive:'疾影：每回合第 3 张牌抽 1 张牌。',deck:['strike','strike','strike','guard','guard','smoke','venom','shiv','ambush','escape']},arcanist:{name:'秘术师',en:'THE ARCANIST',hp:76,color:'#b9a0e9',tag:'蓄能 · 爆发',text:'以脆弱之躯，承载失控的星火。',passive:'共鸣：每回合开始获得 1 层灵力。',deck:['strike','strike','guard','guard','frost','bolt','bolt','meditate','barrier','insight']}};
export const RELICS=[{id:'ruby',name:'余烬红宝石',icon:'flame',desc:'每次战斗胜利恢复 4 点生命。'},{id:'anchor',name:'生锈船锚',icon:'shield',desc:'战斗第一回合获得 10 点护甲。'},{id:'fang',name:'蛇神之牙',icon:'poison',desc:'施加中毒时额外增加 2 层。'},{id:'eye',name:'洞察之眼',icon:'eye',desc:'每回合多抽 1 张牌。'},{id:'coin',name:'古王钱币',icon:'coin',desc:'每次战斗额外获得 15 金币。'},{id:'crown',name:'裂隙王冠',icon:'crown',desc:'每回合能量 +1，但开战失去 3 点生命。'},{id:'stone',name:'磨刀石',icon:'sword',desc:'开战获得 2 点力量。'},{id:'heart',name:'不灭之心',icon:'heart',desc:'获得时最大生命 +12，并恢复 12 点生命。'}];
export type NodeType='battle'|'elite'|'camp'|'shop'|'event'|'boss';
export const NODE_NAMES:Record<NodeType,string>={battle:'遭遇战',elite:'精英',camp:'营地',shop:'商人',event:'未知事件',boss:'领主'};
export type Enemy={name:string;hp:number;maxHp:number;block:number;poison:number;weak:number;vuln:number;power:number;boss?:'ironjaw'|'bishop'|'ashking';staggered?:boolean;pressure?:number;enraged?:boolean;minion?:boolean;pattern:{damage:number;hits?:number;block?:number;buff?:number;weak?:number;ritual?:number;label:string}[];offset:number};
export type Game={version:1;runId?:string;startedAt?:number;seed:number;rng:number;job:Job;hard:boolean;phase:'map'|'battle'|'reward'|'camp'|'shop'|'event'|'won'|'lost';floor:number;lane:number;route:NodeType[][];path:number[];hp:number;maxHp:number;gold:number;deck:string[];relics:string[];hand:string[];draw:string[];discard:string[];exhaust:string[];energy:number;block:number;strength:number;focus:number;weak:number;retain:boolean;played:number;turn:number;enemies:Enemy[];target:number;offers:string[];shop:string[];shopRefreshes?:number;shopRemovalUsed?:boolean;cardsRemoved?:number;removed:boolean;event:number;lastRelic:string|null;log:string[];kills:number};
export type Action={type:'node';lane:number}|{type:'play';index:number;target?:number}|{type:'target';index:number}|{type:'end'}|{type:'reward';index:number}|{type:'rest'}|{type:'upgrade';index:number;path?:UpgradePath}|{type:'refreshShop'}|{type:'buy';index:number}|{type:'remove';index:number}|{type:'leave'}|{type:'event';index:number};
function random(g:Game){let t=g.rng+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296}
function shuffle<T>(g:Game,a:T[]){for(let i=a.length-1;i>0;i--){const j=Math.floor(random(g)*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function log(g:Game,s:string){g.log=[s,...g.log].slice(0,30)}
function has(g:Game,id:string){return g.relics.includes(id)}
function heal(g:Game,n:number){g.hp=Math.min(g.maxHp,g.hp+n)}
function relic(g:Game){const r=shuffle(g,RELICS.filter(r=>!has(g,r.id)&&(r.id!=='fang'||g.job==='shade')))[0];g.lastRelic=r?.id??null;if(r){g.relics.push(r.id);log(g,'获得遗物：'+r.name);if(r.id==='heart'){g.maxHp+=12;heal(g,12)}}else g.gold+=40}
function draw(g:Game,n:number){for(let i=0;i<n&&g.hand.length<10;i++){if(!g.draw.length){g.draw=shuffle(g,g.discard);g.discard=[]}const c=g.draw.pop();if(c)g.hand.push(c)}}
function begin(g:Game){const previousBlock=g.block,kept=g.retain;g.turn++;g.energy=3+(has(g,'crown')?1:0);g.block=(g.retain?g.block:0)+(g.job==='warden'?2:0)+(g.turn===1&&has(g,'anchor')?10:0);g.retain=false;g.played=0;for(const e of g.enemies)e.pressure=0;if(g.job==='arcanist')g.focus++;draw(g,5+(has(g,'eye')?1:0));log(g,`第 ${g.turn} 回合 · ${g.turn>1?(kept?`固守保留 ${previousBlock} 护甲`:`清除剩余 ${previousBlock} 护甲`):'战斗开始'}${g.job==='warden'?'，铁卫被动 +2':''} · 抽牌，能量恢复`)}
export function intent(g:Game,e:Enemy){const planned=e.pattern[(g.turn-1+e.offset)%e.pattern.length];const p=e.staggered?{damage:0,label:'失衡 · 本次行动取消'}:planned.ritual&&(e.pressure??0)>=planned.ritual?{damage:0,label:'祷告已打断'}:planned;return {...p,damage:Math.floor((p.damage+(p.damage?e.power:0))*(e.weak>0?.75:1)),hits:p.hits??1}}
function makeEnemy(name:string,hp:number,pattern:Enemy['pattern'],offset=0):Enemy{return {name,hp,maxHp:hp,pattern,offset,block:0,poison:0,weak:0,vuln:0,power:0}}
function battle(g:Game,t:NodeType){const a=Math.floor(g.floor/5),scale=1.27*(1+a*.4)*(g.hard?1.10:1);const hp=(n:number)=>Math.round(n*scale);const hit=(n:number)=>Math.round(n*1.20*(1+a*.22)*(g.hard?1.08:1));const attack=(n:number,label='攻击')=>({damage:hit(n),label});if(t==='boss'){const names=['守门者 · 铁颚','无光主教','灰烬之王'];const boss=makeEnemy(names[a],hp(95),a===1?[attack(9,'裁决'),{damage:0,ritual:12,label:'献祭祷告 · 召唤侍从'},attack(18,'审判')]:[{...attack(9,'双重斩击'),hits:2},{damage:0,block:16,buff:2,label:'王座庇护 · 蓄力'},{...attack(24,'处决'),weak:1}]);boss.boss=a===0?'ironjaw':a===1?'bishop':'ashking';if(a===0)boss.block=12;g.enemies=[boss]}else if(t==='elite'){g.enemies=[makeEnemy(a===0?'锈甲处刑者':a===1?'虚空骑士':'焚骨巨像',hp(68),[attack(14,'重劈'),{damage:0,block:12,buff:3,label:'淬火 · 力量 +3'},attack(20,'处刑')])]}else{const r=Math.floor(random(g)*3);g.enemies=r===0?[makeEnemy('地穴潜伏者',hp(38),[attack(8),{damage:0,block:7,label:'蜷缩'},attack(12,'猛扑')])]:r===1?[makeEnemy('失魂士兵',hp(45),[attack(9),{...attack(5,'盾击'),block:8},attack(12)])]:[makeEnemy('灰烬幼灵',hp(23),[attack(5,'火花'),attack(7,'灼烧')]),makeEnemy('迷途怨灵',hp(25),[{damage:0,buff:2,label:'低语 · 力量 +2'},attack(7,'撕咬')],1)]}
g.phase='battle';g.hand=[];g.draw=shuffle(g,[...g.deck]);g.discard=[];g.exhaust=[];g.turn=0;g.strength=has(g,'stone')?2:0;g.focus=0;g.weak=0;g.retain=false;g.block=0;g.target=0;g.lastRelic=null;if(has(g,'crown'))g.hp=Math.max(1,g.hp-3);log(g,'进入'+NODE_NAMES[t]);begin(g)}
function wonBattle(g:Game){if(g.hp<=0){g.hp=0;g.phase='lost';log(g,'余烬熄灭。');return true}if(g.enemies.some(e=>e.boss==='bishop'&&e.hp<=0)){for(const e of g.enemies)if(e.minion)e.hp=0}if(g.enemies.some(e=>e.hp>0))return false;const type=g.route[g.floor][g.lane];const gold=(type==='boss'?60:type==='elite'?40:22)+(has(g,'coin')?15:0);g.gold+=gold;g.kills++;if(has(g,'ruby'))heal(g,4);if(type==='elite'||type==='boss')relic(g);g.offers=shuffle(g,Object.keys(CARDS).filter(k=>CARDS[k].job===g.job||(CARDS[k].job==='any'&&!['strike','guard'].includes(k)))).slice(0,3);g.phase='reward';log(g,`战斗胜利 · 获得 ${gold} 金币`);return true}
function advance(g:Game){if(g.floor===14){g.phase='won';log(g,'灰烬王座已倾覆。');return}if(g.route[g.floor]?.[g.lane]==='boss'){heal(g,Math.round(g.maxHp*.2));log(g,'穿越深层 · 恢复 20% 最大生命')}g.phase='map'}

export function eventUnavailable(g:Game){const e=EVENTS[g.event];if(!e)return '事件不可用';if(g.gold<e.gold)return `金币不足，需要 ${e.gold} 金币`;if(g.event===3&&g.deck.every(isUpgraded))return '没有可专精的未升级卡牌';if(g.event===4&&g.maxHp<=5)return '最大生命不足';if(g.event===6&&!g.deck.some(isUpgraded))return '没有可复制的已升级卡牌';if(g.event===7&&(g.deck.length<=5||!g.deck.some(k=>k==='strike'||k==='guard')))return '没有可移除的基础牌，或牌组已达下限';return null}
export function cardRemovalCost(g:Game){return 55+20*(g.cardsRemoved??0)}
export function shopRefreshCost(g:Game){return 20+10*(g.shopRefreshes??0)}
export function newGame(job:Job,hard=false,seed=Date.now()>>>0):Game{const g:Game={version:1,seed,rng:seed,job,hard,phase:'map',floor:-1,lane:1,route:[],path:[],hp:JOBS[job].hp,maxHp:JOBS[job].hp,gold:65,deck:[...JOBS[job].deck],relics:[],hand:[],draw:[],discard:[],exhaust:[],energy:0,block:0,strength:0,focus:0,weak:0,retain:false,played:0,turn:0,enemies:[],target:0,offers:[],shop:[],shopRefreshes:0,shopRemovalUsed:false,cardsRemoved:0,removed:false,event:0,lastRelic:null,log:['旅者踏入了余烬地牢。'],kills:0};g.route=Array.from({length:15},(_,f)=>Array.from({length:3},(_,l)=>f%5===4?'boss':f===0?'battle':f%5===3?(l===1?'camp':l===0?'elite':'shop'):shuffle(g,['battle','battle','elite','event','shop','camp'] as NodeType[])[0]));return g}
export function act(state:Game,action:Action):Game{const g=structuredClone(state);const a=action;if(a.type==='target'){if(g.phase==='battle'&&g.enemies[a.index]?.hp>0)g.target=a.index;return g}
if(a.type==='node'&&g.phase==='map'){const f=g.floor+1;if(!Number.isInteger(a.lane)||a.lane<0||a.lane>2||f>14||(g.floor>=0&&Math.abs(a.lane-g.lane)>1))return state;g.floor=f;g.lane=a.lane;g.path.push(a.lane);const t=g.route[f][a.lane];if(['battle','elite','boss'].includes(t))battle(g,t);else {g.phase=t as Game['phase'];g.removed=false;if(t==='shop'){g.shopRemovalUsed=false;g.shopRefreshes=0;g.shop=shuffle(g,Object.keys(CARDS).filter(k=>CARDS[k].job===g.job)).slice(0,3);}if(t==='event')g.event=Math.floor(random(g)*EVENTS.length)}return g}
if(a.type==='play'&&g.phase==='battle'){const key=g.hand[a.index];if(!key)return state;const c=getCard(key);if(g.energy<c.cost)return state;if(a.target!==undefined){if(!Number.isInteger(a.target)||!g.enemies[a.target]||g.enemies[a.target].hp<=0)return state;g.target=a.target}if(requiresTarget(c)&&(!g.enemies[g.target]||g.enemies[g.target].hp<=0))return state;g.energy-=c.cost;g.hand.splice(a.index,1);(c.exhaust?g.exhaust:g.discard).push(key);log(g,'打出 '+c.name);g.hp-=c.hpCost??0;if(g.hp<=0){wonBattle(g);return g}g.block+=c.block??0;g.strength+=c.strength??0;g.focus+=c.focus??0;g.energy+=c.energy??0;heal(g,c.heal??0);if(c.retain)g.retain=true;
const armorFuel=c.burnArmor?g.block:0;if(c.burnArmor)g.block=0;if(c.focusShield){g.block+=g.focus*c.focusShield;g.focus=0;}
const enemies=c.all?g.enemies:[g.enemies[g.target]];for(const e of enemies){if(!e||e.hp<=0)continue;if(c.damage||c.shieldStrike){let damage=(c.damage??(c.shieldStrike?g.block:0))+g.strength+(c.combo&&g.played>=2?8:0)+(c.burst?g.focus*3:0)+armorFuel+(c.perPlayed??0)*Math.min(3,g.played)+(c.bloodied&&g.hp<=g.maxHp/2?c.bloodied:0);damage=Math.floor(damage*(g.weak>0?.75:1)*(e.vuln>0?1.5:1));const oldBlock=e.block,oldHp=e.hp;const absorbed=c.piercing?0:Math.min(e.block,damage);e.block-=absorbed;e.hp=Math.max(0,e.hp-damage+absorbed);e.pressure=(e.pressure??0)+oldHp-e.hp;if(e.boss==='ironjaw'&&oldBlock>0&&e.block===0&&e.hp>0){e.staggered=true;log(g,'铁颚护甲被击破，本次行动取消！')}if(e.boss==='ashking'&&!e.enraged&&e.hp>0&&e.hp<=e.maxHp/2){e.enraged=true;log(g,'灰烬之王进入余烬审判：每回合第 4 张牌触发 4 点灼伤。')}log(g,`${e.name} 受到 ${damage-absorbed} 点伤害`)}if(c.detonate&&e.hp>0){const oldHp=e.hp;e.hp=Math.max(0,e.hp-e.poison*c.detonate);e.poison=0;e.pressure=(e.pressure??0)+oldHp-e.hp;if(e.boss==='ashking'&&e.hp>0&&e.hp<=e.maxHp/2)e.enraged=true;log(g,`${e.name} 毒爆受到 ${oldHp-e.hp} 点伤害`)}e.poison+=(c.poison??0)+(c.poison&&has(g,'fang')?2:0);e.weak+=c.weak??0;e.vuln+=c.vuln??0}if(c.burst)g.focus=c.conserveFocus?Math.floor(g.focus/2):0;g.played++;if(g.played===4&&g.enemies.some(e=>e.hp>0&&e.boss==='ashking'&&e.enraged)){g.hp-=4;log(g,'第 4 张牌触发余烬爆裂：失去 4 生命。')}draw(g,c.draw??0);if(g.job==='shade'&&g.played===3)draw(g,1);if(g.enemies[g.target]?.hp<=0)g.target=g.enemies.findIndex(e=>e.hp>0);wonBattle(g);return g}
if(a.type==='end'&&g.phase==='battle'){g.discard.push(...g.hand);g.hand=[];g.weak=Math.max(0,g.weak-1);for(const e of [...g.enemies]){if(e.hp<=0)continue;e.block=0;if(e.poison){const oldHp=e.hp;e.hp=Math.max(0,e.hp-e.poison);e.pressure=(e.pressure??0)+oldHp-e.hp;if(e.boss==='ashking'&&e.hp>0&&e.hp<=e.maxHp/2)e.enraged=true;log(g,`${e.name} 中毒受到 ${e.poison} 点伤害`);e.poison--}if(e.hp<=0){if(e.boss==='bishop'){for(const add of g.enemies)if(add.minion)add.hp=0;break}continue}const p=intent(g,e);for(let i=0;i<p.hits;i++){const blocked=Math.min(g.block,p.damage);g.block-=blocked;g.hp-=p.damage-blocked}if(p.damage)log(g,`${e.name} ${p.label}：${p.damage} × ${p.hits}`);if(p.ritual){const living=g.enemies.some(x=>x.minion&&x.hp>0);if(!living){const add=makeEnemy('祷火侍从',24,[{damage:7,label:'祷火'}]);add.minion=true;const slot=g.enemies.findIndex(x=>x.minion&&x.hp<=0);if(slot>=0)g.enemies[slot]=add;else g.enemies.push(add);log(g,'祷告完成：一名侍从加入战场，下回合开始行动。')}else log(g,'侍从仍在场，祷告没有召来更多敌人。')}e.staggered=false;e.block+=p.block??0;e.power+=p.buff??0;g.weak+=p.weak??0;e.weak=Math.max(0,e.weak-1);e.vuln=Math.max(0,e.vuln-1);if(g.hp<=0||e.boss==='bishop'&&e.hp<=0)break}if(wonBattle(g))return g;if(g.enemies[g.target]?.hp<=0)g.target=g.enemies.findIndex(e=>e.hp>0);begin(g);return g}
if(a.type==='reward'&&g.phase==='reward'){if(a.index!==-1&&!g.offers[a.index])return state;if(a.index>=0){g.deck.push(g.offers[a.index]);log(g,'加入卡组：'+getCard(g.offers[a.index]).name)}g.offers=[];advance(g);return g}
if(a.type==='rest'&&g.phase==='camp'){heal(g,Math.ceil(g.maxHp*.3));log(g,'在营火旁恢复了生命。');advance(g);return g}
if(a.type==='upgrade'&&g.phase==='camp'){if(!g.deck[a.index]||isUpgraded(g.deck[a.index]))return state;if(a.path!==undefined&&!['power','tactic'].includes(a.path))return state;g.deck[a.index]+=a.path==='tactic'?'~':'+';log(g,'升级：'+getCard(g.deck[a.index]).name);advance(g);return g}
if(a.type==='refreshShop'&&g.phase==='shop'){const cost=shopRefreshCost(g);if(g.gold<cost)return state;g.shop=shuffle(g,Object.keys(CARDS).filter(k=>CARDS[k].job===g.job&&!g.shop.includes(k))).slice(0,3);g.gold-=cost;g.shopRefreshes=(g.shopRefreshes??0)+1;log(g,`花费 ${cost} 金币刷新商店，新上架：${g.shop.map(k=>getCard(k).name).join('、')}。`);return g}
if(a.type==='buy'&&g.phase==='shop'){if(a.index===3){if(g.gold<90||g.removed)return state;g.gold-=90;relic(g);g.removed=true}else{if(!g.shop[a.index]||g.gold<45)return state;g.gold-=45;g.deck.push(g.shop[a.index]);g.shop[a.index]=''}return g}
if(a.type==='remove'&&g.phase==='shop'){const cost=cardRemovalCost(g);if(g.shopRemovalUsed||g.gold<cost||g.deck.length<=5||!Number.isInteger(a.index)||!g.deck[a.index])return state;g.gold-=cost;log(g,`花费 ${cost} 金币移除：${getCard(g.deck[a.index]).name}。本店删牌机会已用完。`);g.deck.splice(a.index,1);g.shopRemovalUsed=true;g.cardsRemoved=(g.cardsRemoved??0)+1;return g}
if(a.type==='leave'&&(g.phase==='shop'||g.phase==='camp')){advance(g);return g}
if(a.type==='event'&&g.phase==='event'){
 if(a.index!==0&&a.index!==1)return state;
 if(a.index===1){heal(g,5);log(g,'静心休息，恢复 5 点生命。');advance(g);return g}
 if(eventUnavailable(g))return state;
 const event=EVENTS[g.event];g.hp-=event.hp;g.gold-=event.gold;
 if(g.hp<=0){g.hp=0;g.phase='lost';log(g,'献祭的代价耗尽了生命。');return g}
 if(g.event===0){relic(g);const r=RELICS.find(r=>r.id===g.lastRelic);log(g,`失去 9 生命，${r?'获得遗物：'+r.name+' — '+r.desc:'遗物已集齐，获得 40 金币'}。`)}
 else if(g.event===1){g.gold+=55;g.deck.push('strike');log(g,'获得 55 金币，额外加入一张斩击。')}
 else if(g.event===2||g.event===3){const chosen=shuffle(g,g.deck.map((k,i)=>({k,i})).filter(x=>!isUpgraded(x.k))).slice(0,g.event===2?2:1);for(const x of chosen)g.deck[x.i]+=g.event===2?'+':'~';log(g,chosen.length?`${g.event===2?'失去 7 生命':'支付 35 金币'}，升级了 ${chosen.length} 张牌：${chosen.map(x=>`${getCard(x.k).name} → ${getCard(g.deck[x.i]).name}`).join('、')}。`:'失去 7 生命；没有可升级的卡牌。')}
 else if(g.event===4){const oldHp=g.hp;g.maxHp-=5;g.hp=Math.min(g.hp,g.maxHp);heal(g,24);log(g,`最大生命 -5 → ${g.maxHp}，当前生命 ${oldHp} → ${g.hp}。`)}
 else if(g.event===5){const key=shuffle(g,Object.keys(CARDS).filter(k=>CARDS[k].job===g.job))[0]+'~';g.deck.push(key);log(g,`支付 30 金币，获得专精卡牌：${getCard(key).name}。`)}
 else if(g.event===6){const key=shuffle(g,g.deck.filter(isUpgraded))[0];g.deck.push(key);log(g,`支付 40 金币，复制卡牌：${getCard(key).name}。`)}
 else if(g.event===7){const chosen=shuffle(g,g.deck.map((k,i)=>({k,i})).filter(x=>x.k==='strike'||x.k==='guard'))[0];g.deck.splice(chosen.i,1);log(g,`支付 40 金币，遗忘了：${getCard(chosen.k).name}。`)}
 else if(g.event===8){if(random(g)<.5){g.gold+=70;log(g,'骰面为金币：支付 25 金币，获得 70 金币（净赚 45）。')}else{const hp=g.hp;heal(g,10);log(g,`骰面为药草：支付 25 金币，恢复 ${g.hp-hp} 生命。`)}}
 advance(g);return g
}return state}

export function bossMechanic(g:Game,e:Enemy){
 if(e.boss==='ironjaw')return e.staggered?'破盾成功：本次行动已取消。':'破盾失衡：用攻击击破护甲，取消本次行动。穿甲和中毒不会破盾。';
 if(e.boss==='bishop'){const p=e.pattern[(g.turn-1+e.offset)%e.pattern.length];return p.ritual?`祷告进度 ${Math.min(e.pressure??0,p.ritual)}/${p.ritual}：本回合累计造成 ${p.ritual} 生命伤害可打断召唤（中毒有效）。`:'献祭祷告会召唤一名侍从；看准祷告回合集中输出。击败主教，侍从会消散。'}
 if(e.boss==='ashking')return e.enraged?`余烬审判：本回合已出 ${g.played} 张。第 4 张额外失去 4 生命，之后不再触发。`:'半血变招：生命降至一半后，每回合第 4 张牌额外失去 4 生命。高费用大牌可避开惩罚。';
 return e.minion?'击败无光主教即可驱散此侍从。':'';
}
export function previewTarget(g:Game,index:number,target:number){const next=act(g,{type:'play',index,target});if(next===g)return null;return {damage:Math.max(0,g.enemies[target].hp-next.enemies[target].hp),blocked:Math.max(0,g.enemies[target].block-next.enemies[target].block),poison:Math.max(0,next.enemies[target].poison-g.enemies[target].poison),weak:Math.max(0,next.enemies[target].weak-g.enemies[target].weak),vuln:Math.max(0,next.enemies[target].vuln-g.enemies[target].vuln),staggered:!!next.enemies[target].staggered,retaliation:Math.max(0,g.hp-next.hp)}}
